name: 'Auto Version'
description: 'Automatically update the tag to the latest version'
outputs:
  version:
    description: "The new version"
    value: ${{ steps.version-generator.outputs.version }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - id: version-generator
      run: ${{ github.action_path }}/autoversion/main.py >> $GITHUB_OUTPUT
      shell: bash